name: publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Install Poetry
      run: pip install poetry

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        cache: poetry

    - name: Install Python libraries
      run: poetry install

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Publish package and update version
      if: github.ref == 'refs/heads/main'
      env:
        PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
      run: |
        poetry run make publish-release
        version=$(poetry version -s)
        git add pyproject.toml
        git commit -m "Bump version to ${version}"
        git push 