name: run-unit-tests

on: push

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    container: python:3.11-slim
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: 'Create env file'
      run: |
        touch .env
        echo AZURE_KEYS=${{ secrets.AZURE_KEYS }} >> .env
        echo CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }} >> .env
        echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} >> .env
        echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
        echo LAMOOM_API_URI=${{ secrets.LAMOOM_API_URI }} >> .env
        echo LAMOOM_API_TOKEN=${{ secrets.LAMOOM_API_TOKEN }} >> .env
        echo FLOW_PROMPT_API_URI=${{ secrets.FLOW_PROMPT_API_URI }} >> .env
        echo FLOW_PROMPT_API_TOKEN=${{ secrets.FLOW_PROMPT_API_TOKEN }} >> .env
        cat .env

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y curl build-essential

    - name: Install Poetry
      run: pip install poetry

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
        cache: poetry

    - name: Install Python libraries
      run: poetry install

    - name: Run tests with pytest
      run: |
        poetry run make test
